# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6edccf17fb19ccf4a073c4b806b6b7be83268513630bd83995dd531b62d28ddd676999583e37543220e20b8f73168b90c58781b077e5da4e16f04886284f109f

test:
  secret_key_base: df8876d5b84f6e50caa0ca106729a8910c3d43b1af8bd9ddfc9f5bc268ffd0745b8717a61c950dc66a22c1f6cf4a6b929b222458ff07b1b9a0c4139d29a2ff10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
